export interface Estimaciones {
    OwnerID: string;
    ContractID: string;
    ContractNumber: string;
    "Admin Fee": number;
    "Cargo financiero": number;
    "CDPs Autorizados": string[];
    "Certificado de Vida Closing Cost": number;
    "Certificado de Vida en Sobreprecio": number;
    "Closing Cost Pagado": number;
    Club: string;
    "Club Semanal": string;
    contract_bridge_id: string;
    "Contrato Anterior": string;
    "Costo de venta del contrato previo": number;
    "Créditos Vacacionales": number;
    "Cuota Anual USD": number;
    "Down Payment": number;
    "Enganche Inicial": number;
    "Enganche Total": number;
    "Equity transferred": number;
    Etiqueta: string;
    "Fecha de primera Mensualidad": Date;
    "Fecha Primer Uso": Date;
    "Fecha Expiración": Date;
    "Fecha Primer Pago": Date;
    "Fecha Segundo Pago": Date;
    "Fecha Tercer Pago": Date;
    "Fecha Cuarto Pago": Date;
    "Fecha Quinto Pago": Date;
    "Fecha Sexto Pago": Date;
    "Fecha Séptimo Pago": Date;
    "Fecha Octavo Pago": Date;
    "Fecha Noveno Pago": Date;
    "Fecha Decimo Pago": Date;
    "Fecha Decimo Primer Pago": Date;
    "Fecha Decimo Segundo Pago": Date;
    "Fecha Primer Pickup": Date;
    "Fecha Segundo Pickup": Date;
    "Fecha Tercer Pickup": Date;
    "Fecha Cuarto Pickup": Date;
    "Fecha Quinto Pickup": Date;
    "Fecha Sexto Pickup": Date;
    "Fecha Último Pickup": Date;
    "Flyback en Sobreprecio": number;
    Fundación: number;
    "ID de la Sala": string;
    "Importe a Financiar": number;
    "Importe de la Mensualidad": number;
    "Importe FlyBack en CC": number;
    "Importe Primer Pago": number;
    "Importe Segundo Pago": number;
    "Importe Tercer Pago": number;
    "Importe Cuarto Pago": number;
    "Importe Quinto Pago": number;
    "Importe Sexto Pago": number;
    "Importe Séptimo Pago": number;
    "Importe Octavo Pago": number;
    "Importe Noveno Pago": number;
    "Importe Decimo Pago": number;
    "Importe Decimo primer Pago": number;
    "Importe Decimo Segundo Pago": number;
    "Importe Primer Pago Pickup": number;
    "Importe Segundo Pago Pickup": number;
    "Importe Tercer  Pago Pickup": number;
    "Importe Cuarto  Pago Pickup": number;
    "Importe Quinto Pago Pickup": number;
    "Importe Sexto Pago Pickup": number;
    "Importe Rentsure": number;
    "Instrumento de pago": string;
    "Interest Rate/Yr": number;
    "Membresía Club Semanal": string;
    Meses: number;
    Moneda: string;
    "No. Serie Tablet": string;
    "Nombre de la Sala": string;
    Oportunidad: string;
    "Pickup Autorizados": string[];
    "Precio Mínimo de venta": number;
    "Precio Tablet": number;
    "Precio Venta": number;
    "Puntos anteriores": number;
    "Puntos Totales": number;
    Rentsure: string;
    "Tasa de cambio": number;
    "Tipo de Cambio Alterno": number;
    "Tasa de Cambio Alterna": number;
    "Tipo de ajuste": string;
    "Tipo de contrato": string;
    "Tipo de membresía": string;
    "Tipo de Venta": string;
    "Tipo Tablet": string;
    "Total CDP": number;
    "Total Closing Cost": number;
    "Total Pickup": number;
    "Trade In": number;
    "Transfer Fee": number;
    "Última Fecha de CDP": Date;
    MortgageID: string;
}

