import { ObjConId } from "./obj-con-id.model";

    export interface Prospectos {
    "4 Digitos": string;
    "Apellido Materno": string;
    "Apellido Paterno": string;
    Apellidos: string;
    "Calificación": string;
    Calle: string;
    "Campaña Principal": ObjConId;
    "Caza Ofertas": string;
    Ciudad: string;
    "Ciudad Locación": string;
    "Código postal": string;
    Colonia: string;
    coprospect_bridge_id: string;
    "Correo electrónico": string;
    "Correo electrónico secundario": string;
    "CP Apellido Materno": string;
    "CP Apellido Paterno": string;
    "CP Correo Electronico": string;
    "CP Edad": number;
    "CP Empresa donde labora": string;
    "CP Fecha de Nacimiento": string;
    "CP Movil": string;
    "CP Nombre": string;
    "CP Ocupación": string;
    "CP Telefono": string;
    "CP Título": string;
    "Empresa donde labora": string;
    "Estado civil": string;
    "Estado de Prospecto": string;
    "Estado/Provincia": string;
    "Fecha de Nacimiento": string;
    Folio: string;
    "Forma de Pago": string;
    "Fuente de Prospecto": string;
    Hook: boolean;
    ID: string;
    "Importe Cobrado": number;
    "Ingresos Mensuales": string;
    "Lenguaje de Contacto": string;
    Locacion: string;
    Moneda: string;
    "Móvil": string;
    Municipio: string;
    Nacionalidad: string;
    Nombre: string;
    "No. Exterior": string;
    "No. Interior": string;
    "Numero Autorización": string;
    "Numero de Noches": number;
    "Numero de Prospecto": string;
    Numero_de_prospecto_netcenter: string;
    Ocupación: string;
    "País": string;
    prospect_bridge_id: string;
    "Sala Referido": string;
    Sexo: string;
    "Tasa de cambio": number;
    "Teléfono": string;
    Terminal: string;
    "Título": string;
    "Vigencia (Meses)": string;
}
