    
    import { Estimaciones } from '../../models/estimaciones.model';

    export const estimacionesMapping: {
        [K in keyof Estimaciones]: { key: string; transform?: (value: any) => any }} = {
                    OwnerID: { key: 'owner_id', transform: undefined },
            ContractID: { key: 'contract_id', transform: undefined },
            ContractNumber: { key: 'contract_number', transform: undefined },
            "Admin Fee": { key: 'admin_fee', transform: undefined },
            "Cargo financiero": { key: 'financial_charge', transform: undefined },
            "CDPs Autorizados": { key: 'authorized_cdps', transform: undefined },
            "Certificado de Vida Closing Cost": { key: 'life_certificate_closing_cost', transform: undefined },
            "Certificado de Vida en Sobreprecio": { key: 'life_certificate_overprice', transform: undefined },
            "Closing Cost Pagado": { key: 'closing_cost_paid', transform: undefined },
            Club: { key: 'club', transform: undefined },
            "Club Semanal": { key: 'weekly_club', transform: undefined },
            contract_bridge_id: { key: 'contract_bridge_id', transform: undefined },
            "Contrato Anterior": { key: 'previous_contract', transform: undefined },
            "Costo de venta del contrato previo": { key: 'previous_contract_sale_cost', transform: undefined },
            "Créditos Vacacionales": { key: 'vacation_credits', transform: undefined },
            "Cuota Anual USD": { key: 'annual_fee_usd', transform: undefined },
            "Down Payment": { key: 'down_payment', transform: undefined },
            "Enganche Inicial": { key: 'initial_down_payment', transform: undefined },
            "Enganche Total": { key: 'total_down_payment', transform: undefined },
            "Equity transferred": { key: 'equity_transferred', transform: undefined },
            Etiqueta: { key: 'label', transform: undefined },
            "Fecha de primera Mensualidad": { key: 'first_monthly_payment_date', transform: undefined },
            "Fecha Primer Uso": { key: 'first_use_date', transform: undefined },
            "Fecha Expiración": { key: 'expiration_date', transform: undefined },
            "Fecha Primer Pago": { key: 'date_first_payment_cdp', transform: undefined },
            "Fecha Segundo Pago": { key: 'date_second_payment_cdp', transform: undefined },
            "Fecha Tercer Pago": { key: 'date_third_payment_cdp', transform: undefined },
            "Fecha Cuarto Pago": { key: 'date_fourth_payment_cdp', transform: undefined },
            "Fecha Quinto Pago": { key: 'date_fifth_payment_cdp', transform: undefined },
            "Fecha Sexto Pago": { key: 'date_sixth_payment_cdp', transform: undefined },
            "Fecha Séptimo Pago": { key: 'date_seventh_payment_cdp', transform: undefined },
            "Fecha Octavo Pago": { key: 'date_eighth_payment_cdp', transform: undefined },
            "Fecha Noveno Pago": { key: 'date_ninth_payment_cdp', transform: undefined },
            "Fecha Decimo Pago": { key: 'date_tenth_payment_cdp', transform: undefined },
            "Fecha Decimo Primer Pago": { key: 'date_eleventh_payment_cdp', transform: undefined },
            "Fecha Decimo Segundo Pago": { key: 'date_twelfth_payment_cdp', transform: undefined },
            "Fecha Primer Pickup": { key: 'date_first_pickup', transform: undefined },
            "Fecha Segundo Pickup": { key: 'date_second_pickup', transform: undefined },
            "Fecha Tercer Pickup": { key: 'date_third_pickup', transform: undefined },
            "Fecha Cuarto Pickup": { key: 'date_fourth_pickup', transform: undefined },
            "Fecha Quinto Pickup": { key: 'date_fifth_pickup', transform: undefined },
            "Fecha Sexto Pickup": { key: 'date_sixth_pickup', transform: undefined },
            "Fecha Último Pickup": { key: 'date_last_pickup', transform: undefined },
            "Flyback en Sobreprecio": { key: 'flyback_overprice', transform: undefined },
            Fundación: { key: 'foundation', transform: undefined },
            "ID de la Sala": { key: 'room_id', transform: undefined },
            "Importe a Financiar": { key: 'amount_to_finance', transform: undefined },
            "Importe de la Mensualidad": { key: 'monthly_amount', transform: undefined },
            "Importe FlyBack en CC": { key: 'flyback_cc_amount', transform: undefined },
            "Importe Primer Pago": { key: 'amount_first_payment', transform: undefined },
            "Importe Segundo Pago": { key: 'amount_second_payment', transform: undefined },
            "Importe Tercer Pago": { key: 'amount_third_payment', transform: undefined },
            "Importe Cuarto Pago": { key: 'amount_fourth_payment', transform: undefined },
            "Importe Quinto Pago": { key: 'amount_fifth_payment', transform: undefined },
            "Importe Sexto Pago": { key: 'amount_sixth_payment', transform: undefined },
            "Importe Séptimo Pago": { key: 'amount_seventh_payment', transform: undefined },
            "Importe Octavo Pago": { key: 'amount_eighth_payment', transform: undefined },
            "Importe Noveno Pago": { key: 'amount_ninth_payment', transform: undefined },
            "Importe Decimo Pago": { key: 'amount_tenth_payment', transform: undefined },
            "Importe Decimo primer Pago": { key: 'amount_eleventh_payment', transform: undefined },
            "Importe Decimo Segundo Pago": { key: 'amount_twelfth_payment', transform: undefined },
            "Importe Primer Pago Pickup": { key: 'amount_first_pickup_payment', transform: undefined },
            "Importe Segundo Pago Pickup": { key: 'amount_second_pickup_payment', transform: undefined },
            "Importe Tercer Pago Pickup": { key: 'amount_third_pickup_payment', transform: undefined },
            "Importe Cuarto Pago Pickup": { key: 'amount_fourth_pickup_payment', transform: undefined },
            "Importe Quinto Pago Pickup": { key: 'amount_fifth_pickup_payment', transform: undefined },
            "Importe Sexto Pago Pickup": { key: 'amount_sixth_pickup_payment', transform: undefined },
            "Importe Rentsure": { key: 'rentsure_amount', transform: undefined },
            "Instrumento de pago": { key: 'payment_instrument', transform: undefined },
            "Interest Rate/Yr": { key: 'annual_interest_rate', transform: undefined },
            "Membresía Club Semanal": { key: 'weekly_club_membership', transform: undefined },
            Meses: { key: 'months', transform: undefined },
            Moneda: { key: 'currency', transform: undefined },
            "No. Serie Tablet": { key: 'tablet_serial_number', transform: undefined },
            "Nombre de la Sala": { key: 'room_name', transform: undefined },
            Oportunidad: { key: 'opportunity', transform: undefined },
            "Pickup Autorizados": { key: 'authorized_pickups', transform: undefined },
            "Precio Mínimo de venta": { key: 'minimum_sale_price', transform: undefined },
            "Precio Tablet": { key: 'tablet_price', transform: undefined },
            "Precio Venta": { key: 'sale_price', transform: undefined },
            "Puntos anteriores": { key: 'previous_points', transform: undefined },
            "Puntos Totales": { key: 'total_points', transform: undefined },
            Rentsure: { key: 'rentsure', transform: undefined },
            "Tasa de cambio": { key: 'exchange_rate', transform: undefined },
            "Tipo de Cambio Alterno": { key: 'alternate_exchange_rate', transform: undefined },
            "Tasa de Cambio Alterna": { key: 'alternate_exchange_rate_alt', transform: undefined },
            "Tipo de ajuste": { key: 'adjustment_type', transform: undefined },
            "Tipo de contrato": { key: 'contract_type', transform: undefined },
            "Tipo de membresía": { key: 'membership_type', transform: undefined },
            "Tipo de Venta": { key: 'sale_type', transform: undefined },
            "Tipo Tablet": { key: 'tablet_type', transform: undefined },
            "Total CDP": { key: 'total_cdp', transform: undefined },
            "Total Closing Cost": { key: 'total_closing_cost', transform: undefined },
            "Total Pickup": { key: 'total_pickup', transform: undefined },
            "Trade In": { key: 'trade_in', transform: undefined },
            "Transfer Fee": { key: 'transfer_fee', transform: undefined },
            "Última Fecha de CDP": { key: 'last_cdp_date', transform: undefined },
            MortgageID: { key: 'mortgage_id', transform: undefined }
            };
